/* SINGLE SOURCE OF TRUTH — edit or add projects here only. See README.md. */
window.SITE = { landingImage: 'Jacobs Hall of Innovation/ethan/QK4A8929.JPG' };
window.PROJECTS = {
  'cat-feeder':{title:'Automatic Cat Feeder',short:'An electromechanical product concept combining an enclosure, dispensing mechanism, and iterative hardware development.',tag:'MECHATRONICS · PRODUCT DESIGN',year:'Fall 2024',role:'[Confirm individual or team role]',tools:'CAD · Electronics · Prototyping · Testing',hero:'../Cat Feeder/Cat Feeder Transparent.png',imageAlt:'CAD rendering of automatic cat feeder',imageFit:'contain',problem:'[Describe the user need, portioning requirements, and system constraints.]',process:'The supplied render and build photos indicate substantial mechanical and mechatronic iteration. Add the verified mechanism, control architecture, and test sequence here.',decisions:['[Add the selected dispensing approach and why.]','[Add enclosure and electronics integration decisions.]','[Add the most important prototype change.]'],outcome:'[Add dispensing accuracy, portion range, control method, test count, and final status.]',gallery:[['../Cat Feeder/Cat Feeder Transparent.png','Product CAD / presentation rendering.']],next:'design-innovation-22'},
  'design-innovation-22':{title:'Design Innovation 22',short:'Three course projects exploring mechatronics, sound-making mechanisms, and kinetic form through iterative prototypes.',tag:'COURSEWORK · DESIGN · PROTOTYPING',year:'[Add term and year]',role:'[Confirm role and collaborators]',tools:'[Add shared course tools, materials, and methods]',hero:'../site-media/IMG_5006.HEIC.png',imageAlt:'Design Innovation 22 Bluetooth Car prototype',problem:'[Describe the Design Innovation 22 course context and overall learning objective.]',process:'The course materials document three distinct builds. Each subproject below preserves its own prompt, process, and media while remaining part of this single course-level case study.',decisions:['[Add the course-wide design approach.]','[Add how critique or testing shaped the work.]','[Add a cross-project learning.]'],outcome:'[Add course outcome, final presentation context, and key skills developed.]',gallery:[],subprojects:[{title:'Bluetooth Car',summary:'A vehicle prototype documented through hands-on assembly and testing.',image:'../site-media/IMG_5037.HEIC.png',details:'[Add the prompt, control system, mechanical architecture, test results, and your role.]'},{title:'Helix Sound Machine',summary:'A sound-making mechanism documented through a sequence of design and presentation images.',image:'../DI 22/Helix Sound Machine/Screenshot 2025-07-04 at 2.18.03 PM.png',details:'[Add the intended interaction, sound-production method, materials, iterations, and outcome.]'},{title:'Kinetic Origami',summary:'A mechanism study exploring folded surfaces and controlled motion.',image:'../DI 22/Kinetic Origami JPGs /IMG_5773.jpg',details:'[Add the prompt, folding principle, actuation, cycle reliability, and final result.]'}],next:'formula-electric'},
  'formula-electric':{title:'Formula Electric at Berkeley',short:'Structural and aerodynamic analysis documented across simulation, iteration, and fabrication.',tag:'FEA · CFD · OPTIMIZATION',year:'[Add term and year]',role:'[Confirm subteam and role]',tools:'FEA · CFD · CAD · Fabrication',hero:'../FEB/feb photos 2/car 3d sim.png',imageAlt:'Race-car aerodynamic simulation',problem:'[Describe the assigned component, requirements, load cases, and performance target.]',process:'The supplied work shows topology optimization and finite-element studies alongside 2D/3D airflow simulations and fabrication photos.',decisions:['Applied a factor-of-safety constraint during structural exploration.','Used topology studies to identify efficient load paths.','Compared aerodynamic behavior across geometry iterations.'],outcome:'[Add validated mass reduction, factor of safety, drag/downforce change, and final component status.]',gallery:[['../FEB/Screenshot 2025-03-03 at 12.40.48 PM.png','Structural simulation used to assess the design.'],['../FEB/feb photos/IMG_8732_2.jpg','Fabricated race-car component—confirm exact part.']],next:'jacobs-hall'},
  'jacobs-hall':{title:'Jacobs Hall of Innovation',short:'A hands-on fabrication project documented through a professional workshop photo series.',tag:'FABRICATION · PROTOTYPING',year:'[Add project name, course, and dates]',role:'[Confirm project and individual role]',tools:'[Add processes, machines, and materials used]',hero:'../Jacobs Hall of Innovation/ethan/QK4A8916.JPG',imageAlt:'Student prototyping in Jacobs Hall',problem:'[Identify the project shown in this folder and describe its engineering objective.]',process:'The available media clearly documents hands-on work in Jacobs Hall, but no project narrative was supplied. Replace this placeholder once the project identity and process are confirmed.',decisions:['[Add design decision.]','[Add fabrication or process decision.]','[Add test-driven iteration.]'],outcome:'[Add the built result, measured performance, and project outcome.]',gallery:[['../Jacobs Hall of Innovation/ethan/QK4A8876.JPG','Workshop process—add a verified caption.'],['../Jacobs Hall of Innovation/ethan/QK4A8938.JPG','Prototype detail—add a verified caption.']],next:'hope'},
  hope:{title:'HOPE',short:'Built through HOPE, a student-led UC Berkeley DeCal I chose for fun to better understand how printed circuit boards work, this linear-tracking record player challenged our team to integrate PCB design, motor control, and mechanical actuation into one working system.',tag:'PCB ENGINEERING · MOTOR CONTROL · ECAD',year:'Fall 2024',role:'Team project · Ethan Descamps, Tim Brugarolas, Isaac Schultz',tools:'ECAD · ERC · DRC · DFM · Hand Soldering · ESP32 · I2C · Motor Drivers · DC, Stepper & Servo Motors',visualLabel:'HOPE · COVER IMAGE TO ADD',problem:'Develop a PCB for a vinyl record player that actuates digital controls mechanically. The board needed to support ESP32 control, I2C communication, a 12 V DC barrel-jack input, and motor drivers for one DC motor and two stepper motors.',process:'The team moved from circuit design into ECAD, producing an assembled board model that passed electrical-rules, design-rules, and design-for-manufacturing checks. After fabrication, the components were hand soldered to the PCB before the board was integrated with the record-player mechanisms.',decisions:['Used a lead screw to move the tonearm through lifting, tracking, and homing operations.','Used linear-encoder feedback with proportional control to actuate the lead screw from the measured tonearm position.','Used PI control for the platter motor to target the selected 33, 45, or 78 RPM speed.','Selected a direct-drive platter architecture, creating a 1:1 relationship between motor and platter rotation.'],outcome:'The PCB was designed as a complete control system, but the team did not receive every bill-of-materials component on assembly day because of what we understood to be a KiCad-related issue. The partially populated board therefore could not be tested as a finished handmade circuit, so its final operation was not confirmed. Working through that gap was an important lesson in component sourcing, design-tool handoff, assembly planning, and the difference between a design that works in theory and one that has been physically validated.',gallery:[['../site-media/hope-presentation/page-3.png','PCB workflow from circuit design and ECAD checks through hand assembly.'],['../site-media/hope-presentation/page-4.png','Tonearm and platter mechanisms with their documented control approaches.'],['../site-media/hope-presentation/page-6.png','HOPE record-player PCB with the components available for assembly.'],['../site-media/hope-presentation/page-7.png','Integrated linear-tracking record-player system.']],status:'Case study draft',isDraft:false,next:'pankl-internship'},
  'pankl-internship':{title:'Pankl Racing Systems Internship',short:'An engineering internship in a high-performance automotive environment.',tag:'INTERNSHIP · MOTORSPORT',year:'[Add internship dates]',role:'[Add exact internship title and team]',tools:'[Add only tools and processes cleared for public disclosure]',hero:'../Pankl Racing Systems/Wide Pankl Logo.jpg',imageAlt:'Pankl Racing Systems logo',imageFit:'contain',problem:'[Describe the internship scope at a non-confidential level.]',process:'Available materials establish the company context but do not establish responsibilities or project details.',decisions:['[Add a non-confidential technical contribution.]','[Add a collaboration or process example.]','[Add a verified learning or improvement.]'],outcome:'[Add approved, non-confidential outcomes or impact.]',gallery:[['../Pankl Racing Systems/IMG_8336.jpg','Internship presentation—add a verified caption.'],['../Pankl Racing Systems/Pankl F1.jpg','Pankl motorsport context.']],next:'abbott-internship'},
  'abbott-internship':{title:'Abbott Cardiac Rhythm Management Internship',short:'Internship case study awaiting approved project details and media.',tag:'INTERNSHIP · MEDICAL DEVICES',year:'[Add internship dates]',role:'[Add exact internship title and team]',tools:'[Add approved tools and processes]',visualLabel:'ABBOTT CRM · MEDIA TO ADD',problem:'[Add a non-confidential description of the engineering problem or internship scope.]',process:'[Add the verified work process, collaborators, and responsibilities.]',decisions:['[Add an approved technical decision.]','[Add a process or collaboration example.]','[Add a verified learning or iteration.]'],outcome:'[Add approved metrics, deliverables, or impact.]',gallery:[],next:'university-bologna'},
  'university-bologna':{title:'Università di Bologna',short:'Academic or project experience awaiting confirmed scope, dates, and media.',tag:'ACADEMIC EXPERIENCE · DETAILS TO ADD',year:'[Add program or project dates]',role:'[Add program, course, or project role]',tools:'[Add relevant tools and methods]',visualLabel:'UNIVERSITÀ DI BOLOGNA · MEDIA TO ADD',problem:'[Clarify whether this was study abroad, research, coursework, or a project, then describe the objective.]',process:'[Add the verified academic or engineering process.]',decisions:['[Add a verified technical or academic decision.]','[Add collaboration context.]','[Add a lesson or iteration.]'],outcome:'[Add the completed work, result, or learning outcome.]',gallery:[],next:'pankl-internship'}
};

window.PROJECTS['abbott-internship'].title='Abbott CRM Internship';
window.PROJECTS['abbott-internship'].next='university-bologna';
window.PROJECTS['university-bologna'].next='pankl-internship';
window.PROJECTS['pankl-internship'].next='jacobs-hall';
window.PROJECTS['jacobs-hall'].next='design-innovation-22';
window.PROJECTS['design-innovation-22'].next='formula-electric';
window.PROJECTS['formula-electric'].next='cat-feeder';
window.PROJECTS['cat-feeder'].next='hope';
window.PROJECTS.hope.next='abbott-internship';
window.PROJECTS=Object.fromEntries(['abbott-internship','university-bologna','pankl-internship','jacobs-hall','design-innovation-22','formula-electric','cat-feeder','hope'].map(key=>[key,window.PROJECTS[key]]));
window.PROJECTS['abbott-internship'].year='January–May 2026';
window.PROJECTS['university-bologna'].year='Fall 2025';
window.PROJECTS['university-bologna'].role='Virtual Vehicle Design Student';
window.PROJECTS['university-bologna'].tools='Siemens NX · AutoCAD · Blender · PowerPoint';
window.PROJECTS['university-bologna'].short='I had the opportunity to study abroad at the Università di Bologna, the world’s oldest university, where I took two engineering-focused courses: Product Reliability and Vehicle Virtual Design.';
window.PROJECTS['pankl-internship'].year='Summer 2025';
window.PROJECTS['pankl-internship'].role='Mechanical R&D Intern';
window.PROJECTS['abbott-internship'].role='Mechanical R&D Intern';
window.PROJECTS['abbott-internship'].tools='Creo (CAD) · Instron · 3D Printing · Prototyping';
window.PROJECTS['jacobs-hall'].year='Spring 2024–Spring 2025';
window.PROJECTS['jacobs-hall'].role='Student Supervisor';
window.PROJECTS['jacobs-hall'].year='February 2024–May 2025';
window.PROJECTS['jacobs-hall'].tools='CNC Milling · Waterjet Cutting · Laser Cutting · FDM · PolyJet · SLA · Woodworking';
window.PROJECTS['jacobs-hall'].cardImage='../Jacobs Hall of Innovation/ethan/QK4A8873.JPG';
window.PROJECTS['jacobs-hall'].hero='../Jacobs Hall of Innovation/ethan/QK4A8873.JPG';
window.PROJECTS['jacobs-hall'].gallery.push(['../Jacobs Hall of Innovation/ethan/QK4A8869.JPG','Fabrication work at Jacobs Hall.']);
window.PROJECTS['jacobs-hall'].short='Supported a high-use UC Berkeley makerspace by maintaining equipment and helping students safely turn ideas into physical prototypes.';
window.PROJECTS['jacobs-hall'].problem='Help makerspace users safely and effectively access a broad range of fabrication tools while keeping equipment reliable and ready for hands-on project work.';
window.PROJECTS['jacobs-hall'].process='I maintained makerspace equipment and tools, supported more than 200 regular users, and provided hands-on guidance across common digital-fabrication and shop workflows.';
window.PROJECTS['jacobs-hall'].decisions=['Matched machine and process recommendations to each user’s material, geometry, and fabrication needs.','Guided users in the safe operation of hand and power tools, CNC mills, laser cutters, waterjet cutters, and industrial 3D printers.','Maintained equipment readiness so users could move efficiently from design to prototype.'];
window.PROJECTS['jacobs-hall'].outcome='Helped sustain a safe, accessible fabrication environment for 200+ regular makerspace users and their project work.';
window.PROJECTS['jacobs-hall'].status='Completed';
window.PROJECTS['jacobs-hall'].isDraft=false;
window.PROJECTS['design-innovation-22'].year='Spring 2025';
window.PROJECTS['formula-electric'].year='Fall 2023–June 2025';
window.PROJECTS['formula-electric'].role='Aerodynamics Engineering Subteam';
window.PROJECTS['cat-feeder'].year='Spring 2024';
window.PROJECTS.hope.hero='../hope/3.JPG?v=20260823';
window.PROJECTS.hope.cardImage='../hope/3.JPG?v=20260823';
window.PROJECTS.hope.imageAlt='HOPE record-player project team with the assembled system';
window.PROJECTS.hope.imageFit='hope-hero';
window.PROJECTS.hope.gallery.unshift(
  ['../hope/1.png?v=20260823','Hand-soldering components onto the HOPE record-player PCB.'],
  ['../hope/2.png?v=20260823','Partially populated HOPE record-player PCB.']
);
window.PROJECTS['abbott-internship'].hero='../Abbott Pictures/IMG_4524.JPEG';
window.PROJECTS['abbott-internship'].imageAlt='Abbott MD&M West Conference team photo';
window.PROJECTS['abbott-internship'].gallery=[['../Abbott Pictures/IMG_1380.jpg?v=2','Abbott pacemaker and miscellaneous items'],['../Abbott Pictures/IMG_1709.jpg?v=2','Libre 3 reverse engineering CAD work'],['../Abbott Pictures/IMG_1631.jpg?v=2','Libre 3 reverse engineering — Nikon XT H 225 ST X-ray scan'],['../Abbott Pictures/IMG_1692.jpg?v=2','Abbott heart dissection, part one'],['../Abbott Pictures/IMG_1684.jpg?v=2','Abbott heart dissection, part two'],['../Abbott Pictures/IMG_1734.jpg?v=2','MRI solution — Bambu slicer'],['../Abbott Pictures/IMG_1721.jpg?v=2','MRI solution — prototype fifteen'],['../Abbott Pictures/IMG_2111.jpg?v=2','Leadless pacemaker fixation — Instron testing'],['../Abbott Pictures/IMG_2469.jpg?v=2','Cleanroom']];
window.PROJECTS['abbott-internship'].gallery.unshift(['../Abbott Pictures/IMG_4524.JPEG','Abbott MD&M West Conference team photo']);
window.PROJECTS['university-bologna'].visualLabel='UNIVERSITY OF BOLOGNA · PROJECT RENDER';
window.PROJECTS['university-bologna'].video={src:'../Bologna VVD/Render Video.mp4',caption:'Università di Bologna project render.'};
window.PROJECTS['university-bologna'].hero='../Bologna VVD/9f6f7cc6-7cfa-49ba-9260-7ba12f7cb2d6.JPG';
window.PROJECTS['university-bologna'].imageAlt='Ethan Descamps with Università di Bologna classmates on the campus steps';
window.PROJECTS['university-bologna'].imageFit='bologna-hero';

window.PROJECTS['pankl-internship'].hero='../Pankl Racing Systems/IMG_8334.jpg';
window.PROJECTS['pankl-internship'].imageAlt='Ethan Descamps with the Pankl Racing Systems team';
window.PROJECTS['pankl-internship'].imageFit='';
window.PROJECTS['pankl-internship'].short='Optimized a Formula One test-bench engine liner through structural, thermal, and fatigue analysis, translating simulation findings into targeted design improvements.';
window.PROJECTS['pankl-internship'].tools='Siemens NX · ANSYS Workbench · DesignModeler · Femap · CFD data';
window.PROJECTS['pankl-internship'].problem='Improve the fatigue life and heat dissipation of a Formula One test-bench engine liner while maintaining the requirements of the surrounding engine assembly.';
window.PROJECTS['pankl-internship'].process='I built an analysis workflow from Siemens NX CAD into ANSYS, incorporating externally supplied CFD water-jacket data. I defined materials, meshing, contacts, and the operating load cases needed to evaluate the liner under realistic conditions.';
window.PROJECTS['pankl-internship'].decisions=['Analyzed steady-state thermal and static-structural conditions, including bolt preload, thermal load, combustion pressure, coolant pressure, and maximum piston lateral force.','Used fatigue analysis to interpret cyclic loading through stress amplitude, mean stress, and factor-of-safety results.','Refined the liner and water-jacket geometry with targeted changes to reduce stress concentration and improve heat dissipation.','Evaluated thread and fillet geometry around preload fasteners to balance fatigue resistance with assembly requirements.'];
window.PROJECTS['pankl-internship'].outcome='Achieved a 19.83% weight reduction in the engine-liner design while refining heat dissipation and maintaining the structural requirements of the test-bench application.';
window.PROJECTS['pankl-internship'].gallery=[['../Pankl Racing Systems/IMG_8336.jpg','Internship project plan and results presentation.'],['../Pankl Racing Systems/Pankl F1.jpg','Pankl Racing Systems motorsport context.']];
window.PROJECTS['pankl-internship'].status='Completed';
window.PROJECTS['pankl-internship'].isDraft=false;

const kineticOrigami=window.PROJECTS['design-innovation-22'].subprojects.find(project=>project.title==='Kinetic Origami');
kineticOrigami.summary='A servo-actuated kinetic sculpture that transforms a single folded sheet into a moving, rotating staircase.';
kineticOrigami.details='I explored how an everyday sheet of paper could become an animated object. Early rhombus-box concepts gave way to a cleaner square enclosure, while repeated cardboard, origami, and servo iterations refined the structure, motion, and visual simplicity of the final design.';
kineticOrigami.gallery=[
  ['../DI 22/Kinetic Origami JPGs /IMG_5399.jpg','Early cardboard enclosure exploration.'],
  ['../DI 22/Kinetic Origami JPGs /IMG_5747.jpg','Fold and actuator experiments during assembly.'],
  ['../DI 22/Kinetic Origami JPGs /IMG_5759.jpg','Servo mechanism and fold geometry under development.'],
  ['../DI 22/Kinetic Origami JPGs /IMG_5832.jpg','Final kinetic-origami staircase prototype.']
];
const bluetoothCar=window.PROJECTS['design-innovation-22'].subprojects.find(project=>project.title==='Bluetooth Car');
bluetoothCar.summary='A Bluetooth-controlled vehicle that paired an Arduino drive system with a laser-cut plywood chassis and iterative balance testing.';
bluetoothCar.details='Emilie Petit and I began with a rough cardboard prototype to learn the Bluetooth control system and test the overall vehicle architecture. After debugging the Arduino connection, we rebuilt the car around a laser-cut plywood chassis, then refined the wheel clearance and added a long tail with a 3D-printed ping-pong-ball holder to improve stability over the course obstacles.';
bluetoothCar.gallery=[
  ['../DI 22/Bluetooth Car Photos/JPEG Bluetooth Photos/Initial_Sketches.jpg','Early concept sketches for the Bluetooth car.'],
  ['../DI 22/Bluetooth Car Photos/JPEG Bluetooth Photos/Screenshot 2025-07-03 at 5.51.58 PM.png','CAD model of the Bluetooth car, including the tail and wheel assembly.'],
  ['../DI 22/Bluetooth Car Photos/JPEG Bluetooth Photos/iloveimg-converted (1) 2/IMG_6642.jpg','Arduino and drivetrain integration during final assembly.'],
  ['../DI 22/Bluetooth Car Photos/JPEG Bluetooth Photos/iloveimg-converted/IMG_5374.jpg','Completed Bluetooth car after the obstacle course.']
];
const helixSoundMachine=window.PROJECTS['design-innovation-22'].subprojects.find(project=>project.title==='Helix Sound Machine');
helixSoundMachine.summary='A rotating sound machine that uses a DC motor to move a ball through a 3D-printed helix inside a laser-cut plywood frame.';
helixSoundMachine.details='Emilie Petit and I refined an early three-helix concept into one more reliable rotating helix. We modeled the structure in Onshape, laser cut the plywood frame, 3D printed the helix and connector pieces, and used an Arduino-controlled DC motor to rotate the mechanism. The final machine uses gravity and the rotating helix to move a ball while producing sound.';
helixSoundMachine.image='../DI 22/Helix Sound Machine/Screenshot 2025-07-04 at 2.15.47 PM.png';
helixSoundMachine.gallery=[
  ['../site-media/helix-low-fidelity-concept-sketch.png','Low-fidelity concept sketch for the helix mechanism and enclosure.'],
  ['../site-media/helix-sound-machine-cad-clean.png','CAD model of the rotating helix noise machine.'],
  ['../DI 22/Helix Sound Machine/Screenshot 2025-07-04 at 2.18.22 PM.png','3D-printed connector piece used in the final assembly.'],
  ['../DI 22/Helix Sound Machine/Screenshot 2025-07-04 at 2.19.28 PM.png','Laser-cut frame and motor assembly during fabrication.']
];
window.PROJECTS['design-innovation-22'].short='A hands-on design and fabrication course exploring physical objects through iterative prototyping, modeling, fabrication, and basic electronics.';
window.PROJECTS['design-innovation-22'].role='Student';
window.PROJECTS['design-innovation-22'].tools='Onshape · 2D and 3D Modeling · Laser Cutting · 3D Printing · Arduino · DC Motors · Basic Circuits · Prototyping';
window.PROJECTS['design-innovation-22'].problem='Design Innovation 22 develops the concepts, skills, and methods needed to design, prototype, and fabricate physical objects. Weekly projects applied new tools and methods to increasingly integrated builds.';
window.PROJECTS['design-innovation-22'].process='Across the course, I used 2D and 3D modeling, laser cutting, 3D printing, soldering, and basic circuits to translate ideas into working physical prototypes. The three projects below capture that progression through mechatronics, sound-making mechanisms, and kinetic form.';
window.PROJECTS['design-innovation-22'].decisions=['Used quick physical prototypes to identify constraints early and guide the next design iteration.','Combined digital modeling and fabrication methods with basic electronics to create functional objects.','Documented the progression from early concepts through testable, finished prototypes.'];
window.PROJECTS['design-innovation-22'].outcome='The outcome was a portfolio of three projects below, each combining physical prototyping, digital modeling, fabrication, and basic electronics in a different way.';
window.PROJECTS['design-innovation-22'].status='Completed';
window.PROJECTS['design-innovation-22'].isDraft=false;
window.PROJECTS['cat-feeder'].short='An automatic cat feeder that combines a 3D-printed enclosure, servo-driven dispenser, sensor feedback, and wireless control to automate feeding and monitor food levels.';
window.PROJECTS['cat-feeder'].role='Student · Team project with Angel Hernandez';
window.PROJECTS['cat-feeder'].tools='Onshape · Bambu Lab 3D Printer · ESP32 · MicroPython · Servo Motor · Load Cell · IMU · Ultrasonic Sensor · ESP-NOW';
window.PROJECTS['cat-feeder'].problem='Create an automatic cat feeder that can dispense food reliably while monitoring the bowl and food supply, supporting hands-free interaction, and notifying the user when food has been dispensed.';
window.PROJECTS['cat-feeder'].process='Angel Hernandez and I designed the non-electronic components in Onshape and fabricated the enclosure in black and white PLA on a Bambu Lab 3D printer. Two ESP32 microcontrollers coordinated sensing and dispensing: a load cell measured food weight, an ultrasonic sensor monitored the food level, and an IMU enabled manual activation by tilting the device.';
window.PROJECTS['cat-feeder'].decisions=['Used a water-wheel-inspired servo dispenser to move food from the feeder into the bowl.','Connected the two ESP32s through ESP-NOW so measured food weight could control whether dispensing was permitted.','Set a 20-gram weight threshold to stop dispensing when the bowl contained sufficient food.','Used the ultrasonic sensor to flag a low supply, triggering a red LED when the measured distance exceeded the defined threshold.','Added Wi-Fi email notifications so the user receives an alert when food is dispensed.'];
window.PROJECTS['cat-feeder'].outcome='Delivered a functioning physical prototype that combines an automatic dispenser, wireless ESP32 communication, sensor-driven control, manual activation, food-level monitoring, and email notifications in a cat-shaped enclosure.';
window.PROJECTS['cat-feeder'].hero='../site-media/cat-feeder-cover-img-4540.jpg';
window.PROJECTS['cat-feeder'].imageAlt='Ethan Descamps and Angel Hernandez developing the automatic cat feeder';
window.PROJECTS['cat-feeder'].imageFit='';
window.PROJECTS['cat-feeder'].gallery=[
  ['../site-media/cat-feeder-slideshow-01.png','Automatic Cat Feeder project introduction.'],
  ['../site-media/cat-feeder-slideshow-02.png','Problem and solution context for the automatic feeder.'],
  ['../site-media/cat-feeder-slideshow-03.png','Target users for the automatic cat feeder.'],
  ['../site-media/cat-feeder-slideshow-04.png','System requirements: ESP32s, actuators, sensors, and IoT communication.'],
  ['../site-media/cat-feeder-slideshow-05.png','Early concept sketches and dispenser mechanism exploration.'],
  ['../site-media/cat-feeder-slideshow-06.png','CAD views of the cat-feeder enclosure.'],
  ['../site-media/cat-feeder-slideshow-07.png','Cat-feeder CAD showing internal mechanical layout.'],
  ['../site-media/cat-feeder-slideshow-08.png','Manufacturing and internal mechanism assembly.'],
  ['../site-media/cat-feeder-slideshow-09.png','Electronics integration and sensor prototyping.'],
  ['../site-media/cat-feeder-slideshow-10.png','Completed automatic cat feeder and development team.'],
  ['../site-media/cat-feeder-img-4567.jpg','Completed automatic cat feeder prototype.']
];
window.PROJECTS['cat-feeder'].status='Completed';
window.PROJECTS['cat-feeder'].isDraft=false;

const formulaElectric=window.PROJECTS['formula-electric'];
formulaElectric.short='Across two seasons, I contributed to Formula Electric at Berkeley’s first aero package, including the rear-wing airfoil elements and their placement for SN3. My more recent work on SN4 focused on the structural front-wing attachment that carries loads from the ribs and pylons into the chassis bulkhead.';
formulaElectric.tag='STRUCTURAL DESIGN · FEA · TOPOLOGY OPTIMIZATION';
formulaElectric.tools='SolidWorks · ANSYS · FEA · Topology Optimization · CAD · Design for Manufacturing';
formulaElectric.hero='../FEB/SN4/IMG_7801 2.JPG';
formulaElectric.cardImage='../FEB/SN4/IMG_7801 2.JPG';
formulaElectric.imageAlt='Formula Electric at Berkeley race car with its front wing installed';
formulaElectric.imageFit='formula-car-hero';
formulaElectric.problem='Create a practical structural path from the SN4 front-wing elements to the chassis bulkhead. The attachment needed to carry the wing loads through the ribs, pylons, and extender hardware while remaining serviceable for quick installation and removal. The binder set assembly-level goals of at least a 2.0 factor of safety and a 50% weight reduction, then documented the analysis used to evaluate the parts.';
formulaElectric.process='I treated the attachment as a chain of interfaces rather than one isolated bracket. I first mapped the wing-to-chassis geometry, selected the pylon extender concept and fastener strategy, and located the aerodynamic load at the center of pressure. I then separated the system into pylon, extender, E1 rib, and E2 rib studies so each link could be checked, revised, and prepared for manufacture.';
formulaElectric.decisions=['Used the wing center of pressure to place the remote structural loads rather than applying them at an arbitrary attachment point.','Compared downforce, drag, lateral force, and combined-load cases to reveal which direction governed the pylon design.','Used a failed maximum-lateral-force study as evidence to revise the pylon instead of accepting the first geometry.','Applied topology optimization to the pylon and inboard ribs, then re-ran FEA on the resulting geometry.','Specified tube-end, fastener, rib-machining, and jig details so the analyzed attachment could be assembled and manufactured.'];
formulaElectric.outcome='The binder documents a complete attachment architecture from chassis tubes and extender hardware through the pylons to the E1 and E2 ribs. The combined pylon study reported a 2.2 factor of safety at 220 N downforce, 30 N drag, and 40 N lateral force; the topology-optimized pylon was rechecked at 1.1, the extender at 1.9, the E1 pylon rib at 2.7, and the E2 pylon rib at 3.4. These are reported analysis results, not physical-test claims.';
formulaElectric.status='Design documented';
formulaElectric.isDraft=false;
formulaElectric.story=[
  {kicker:'01 / ARCHITECTURE',title:'Trace the load path before shaping parts',text:'The starting question was how to connect the front-wing elements to the car without treating the wing, pylons, and chassis as separate problems. Early sketches established the interfaces: ribs support each aerodynamic element, the ribs bolt to the pylons, extender hardware bridges the geometry, and steel tubes carry the assembly into the chassis bulkhead.',media:[['../site-media/feb-binder/page-8.png','Early attachment sketches locating the pylon extender, tabs, and chassis interface.'],['../site-media/feb-binder/page-19.png','Circular steel tubes selected to extend the pylons and weld directly to the chassis.']]},
  {kicker:'02 / SERVICEABILITY',title:'Make the attachment removable and manufacturable',text:'The binder compared a clevis-pin quick release with a traditional bolt. The quick release offered faster assembly, but the traditional bolt was cheaper, stronger, simpler, threaded, and easier to manufacture. The extender concept then moved toward steel tube and rod-end hardware similar to the dynamics team’s tube ends.',media:[['../site-media/feb-binder/page-20.png','Fastener trade study comparing quick release and traditional bolt approaches.'],['../site-media/feb-binder/page-25.png','Steel tube and steel rod-end concept used to define the extender connection.']]},
  {kicker:'03 / LOAD DEFINITION',title:'Put the aerodynamic forces where the wing carries them',text:'The structural setup was tied to the wing’s center of pressure. The report resolved the loading into downforce, drag, and lateral components, then checked individual directions and combined cases. This made it possible to identify whether vertical aero load or cornering-induced lateral load governed each attachment part.',media:[['../site-media/feb-binder/page-75.png','Center-of-pressure coordinates used to locate the remote structural load.'],['../site-media/feb-binder/page-85.png','Maximum-lateral-force case that exposed an inadequate pylon result with a reported factor of safety of 0.29.']]},
  {kicker:'04 / ITERATION',title:'Use failure to redirect the pylon geometry',text:'A maximum lateral-force case produced a reported factor of safety of 0.29, showing that the initial pylon could not simply be carried forward. Topology optimization was then used to expose more efficient load paths. The post-topology pylon study combined 220 N downforce, 30 N drag, and 40 N lateral force and reported a factor of safety of 1.1.',media:[['../site-media/feb-binder/page-87.png','Post-topology pylon FEA under the combined load case.'],['../site-media/feb-binder/page-88.png','Extender FEA, reported at a factor of safety of 1.9.']]},
  {kicker:'05 / RIBS',title:'Carry the same logic into both wing elements',text:'The inboard ribs were analyzed as the next link in the load path. After topology optimization, the E1 pylon rib was reported at a 2.7 factor of safety and the E2 pylon rib at 3.4. Evaluating both elements kept the attachment narrative continuous from aerodynamic surface to pylon instead of stopping at the main bracket.',media:[['../site-media/feb-binder/page-91.png','E1 pylon rib FEA after topology optimization, reported at a factor of safety of 2.7.'],['../site-media/feb-binder/page-94.png','E2 pylon rib FEA after topology optimization, reported at a factor of safety of 3.4.']]},
  {kicker:'06 / MANUFACTURING',title:'Translate analysis into parts, dimensions, and fixtures',text:'The final pages bring the parts back into the complete wing assembly and define how the design would be made. The E1 and E2 ribs are documented as 0.5-inch-thick parts with 3.2 mm holes for helical inserts, and dedicated rib jigs preserve the airfoil geometry during fabrication.',media:[['../site-media/feb-binder/page-100.png','CAD assembly showing the ribs and pylons integrated with the front-wing elements.'],['../site-media/feb-binder/page-108.png','E1 rib machining measurements and hole specification.'],['../site-media/feb-binder/page-109.png','E2 rib machining measurements and hole specification.'],['../site-media/feb-binder/page-111.png','Rib-jig CAD used to hold the wing geometry during fabrication.']]}
];
formulaElectric.outroMedia={src:'../FEB/feb photos 2/car pic.png',alt:'Formula Electric at Berkeley race car with its aero package installed'};
const bologna=window.PROJECTS['university-bologna'];
bologna.tag='VEHICLE VIRTUAL DESIGN · CAD · FEA';
bologna.problem='In Vehicle Virtual Design, our six-person team developed a forward-looking naked motorcycle and its onboard system. The project asked us to connect market needs, competitive benchmarks, vehicle architecture, styling, packaging, structural analysis, and rider-facing controls in one coherent virtual product.';
bologna.process='We planned the development program and R&D budget, studied the evolution of naked motorcycles and their onboard systems, and translated market research into prioritized requirements. A broad competitor matrix and innovation index informed the product architecture. We then developed Stone, Advanced, Retro, and Natural styling directions through sketches, concept renders, and 2D drawings before advancing Stone and Advanced into ergonomic, packaging, aerodynamic, and seat-area comparisons. The selected Stone direction was carried into the final CAD assembly, chassis and swingarm FEA, final rendering, and a coordinated onboard-system interface.';
bologna.decisions=['Used requirement-dependency and relative-importance matrices to narrow the design priorities to comfort, affordability, handling, emotion, smart features, innovation, safety, and style.','Built the concept architecture around a 765 cc three-cylinder engine, chassis and swingarm, active suspension, onboard cameras and GPS, IMU, wheelie control, riding modes, and connected onboard software.','Selected the Stone direction after comparing it with Advanced through rider triangles, tank and engine fit, seat area, and the aerodynamic studies reported in the presentation.','Designed the onboard experience as one system spanning navigation, live trip data, tire temperature, wheelie-control settings, riding modes, device connections, and front/rear camera views.'];
bologna.outcome='The final presentation documents a completed virtual motorcycle concept: a detailed CAD assembly, rendered Stone SP65 exterior, onboard interface suite, and structural checks for the chassis and swingarm. The reported minimum fatigue safety coefficient was 1.1624 for the chassis cornering case; the other reported static and fatigue coefficients were higher. The final concept combined nine highlighted innovations, including a lightweight hollow-perimeter chassis and swingarm, active suspension, advanced IMU, ride modes, connected GPS, cameras, wheelie assist, an intake-variable system, and six infrared sensors.';
bologna.gallery=[
  ['../site-media/bologna-final-presentation/01-market-analysis.png','Market analysis connecting the target rider, desired qualities, use context, and design priorities.'],
  ['../site-media/bologna-final-presentation/02-prioritized-requirements.png','The eight requirements prioritized for the concept-development process.'],
  ['../site-media/bologna-final-presentation/03-innovation-index.png','Competitor innovation index used to identify opportunity within the naked-bike category.'],
  ['../site-media/bologna-final-presentation/04-product-architecture.png','Product-architecture matrix comparing candidate solutions across the motorcycle systems.'],
  ['../site-media/bologna-final-presentation/05-stylistic-directions.png','Four stylistic directions organized from sketches through drawings, CAD, and rendering.'],
  ['../site-media/bologna-final-presentation/06-design-finalists.png','Stone and Advanced selected as the two design finalists.'],
  ['../site-media/bologna-final-presentation/07-ergonomic-comparison.png','Rider-triangle comparison between both finalists and the Triumph Street Triple benchmark.'],
  ['../site-media/bologna-final-presentation/08-advanced-packaging.png','Advanced concept study for the 18-liter tank and engine envelope.'],
  ['../site-media/bologna-final-presentation/09-stone-evaluation.png','Stone concept study reporting a 0.631 drag coefficient, 260 km/h theoretical top speed, and 8,000 mm² seat area.'],
  ['../site-media/bologna-final-presentation/10-final-cad.png','Final motorcycle CAD assembly shown from four viewpoints.'],
  ['../site-media/bologna-final-presentation/11-fea-analysis.png','Chassis and swingarm equivalent-stress results with reported static and fatigue safety coefficients.'],
  ['../site-media/bologna-final-presentation/12-final-render.png','Final Stone SP65 render from multiple viewpoints.'],
  ['../site-media/bologna-final-presentation/13-road-dashboard.png','Road-mode dashboard combining navigation, trip data, speed, and media controls.'],
  ['../site-media/bologna-final-presentation/14-vehicle-settings.png','Vehicle settings for tire temperature and wheelie-control parameters.'],
  ['../site-media/bologna-final-presentation/15-riding-modes.png','Eco, Road, Sport, Track, and Custom ride-mode interface.'],
  ['../site-media/bologna-final-presentation/16-device-connections.png','Device-connection options for Apple, Android, and Bluetooth integration.'],
  ['../site-media/bologna-final-presentation/17-camera-view.png','Onboard front-camera view within the proposed interface.'],
  ['../site-media/bologna-final-presentation/18-track-dashboard.png','Track display prioritizing engine speed, lap time, speed, and tire temperature.'],
  ['../site-media/bologna-final-presentation/19-final-innovations.png','Nine system innovations summarized around the final motorcycle concept.']
];

window.PROJECTS['abbott-internship'].short='Medical-device R&D work spanning rapid prototyping, reverse engineering, design-for-manufacturability, and cross-functional product development.';
window.PROJECTS['abbott-internship'].problem='Support the development of MRI-compatible implantable device solutions and a next-generation leadless pacemaker while improving the accuracy, manufacturability, and integration of supporting components and systems.';
window.PROJECTS['abbott-internship'].process='I worked across concept development, CAD modeling, prototyping, inspection, and design documentation. My work incorporated feedback from clinicians, human-factors specialists, and cross-functional engineering teams during clinical evaluation and development reviews.';
window.PROJECTS['abbott-internship'].decisions=['Generated 50+ design iterations through rapid prototyping and 3D printing, applying human-factors and ergonomic design principles.','Reverse engineered a Nikon XT H 225 ST X-ray CT scanner to recreate the full assembly, internal components, and an insertion mechanism in CAD for product-architecture analysis.','Designed go/no-go gauges using GD&T principles to support repeatable dimensional inspection for a next-generation leadless pacemaker.','Converted 2D electrical schematics and PCB layouts into detailed 3D CAD models for a Bluetooth-enabled pacemaker system, supporting packaging studies and cross-functional integration.','Drove DFM improvements through change orders across multiple products, reducing piece-part count and improving production and documentation workflows for tooling and materials release.'];
window.PROJECTS['abbott-internship'].outcome='Delivered a portfolio of prototype iterations, inspection tooling, CAD models, and manufacturing improvements that supported device development, packaging studies, clinical evaluation, and product-architecture analysis.';
window.PROJECTS['abbott-internship'].status='Completed';
window.PROJECTS['abbott-internship'].isDraft=false;

const key=new URLSearchParams(location.search).get('project'),p=window.PROJECTS[key],root=document.querySelector('#case');
if(root&&p){document.title=`${p.title} — Ethan Descamps`;const lead=p.hero?`<img class="${p.imageFit==='contain'?'contain-media':(p.imageFit||'')}" src="${p.hero}" alt="${p.imageAlt||p.title}">`:`<div class="media-placeholder"><span>${p.visualLabel||'PROJECT MEDIA TO ADD'}</span></div>`;const gallery=p.gallery.length?`<section class="gallery-two">${p.gallery.map(([src,caption])=>`<figure><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('')}</section>`:'';root.innerHTML=`<section class="case-hero"><a class="back" href="../index.html#work">← All projects</a><p class="eyebrow" style="margin-top:72px">${p.tag}</p><h1>${p.title}</h1><div class="case-intro"><p class="summary">${p.short}</p><dl class="case-meta"><div><dt>Timeline</dt><dd>${p.year}</dd></div><div><dt>Role</dt><dd>${p.role}</dd></div><div><dt>Toolkit</dt><dd>${p.tools}</dd></div><div><dt>Status</dt><dd>Case study draft</dd></div></dl></div></section><div class="case-media">${lead}</div><article class="case-body"><section class="case-block"><h2>01 / Problem</h2><div><h3>Defining the engineering question</h3><p>${p.problem}</p></div></section><section class="case-block"><h2>02 / Process</h2><div><h3>Moving from evidence to iteration</h3><p>${p.process}</p><ul>${p.decisions.map(d=>`<li>${d}</li>`).join('')}</ul></div></section><section class="case-block"><h2>03 / Outcome</h2><div><h3>What the work proved</h3><p class="callout">PLACEHOLDER — ${p.outcome}</p></div></section></article>${gallery}<a class="next-project" href="?project=${p.next}"><span>Next case study</span><span>↗</span></a>`}else if(root){root.innerHTML='<section class="case-hero"><a class="back" href="../index.html#work">← All projects</a><h1>Project not found.</h1></section>'}
if(root&&p?.isDraft===false){const outcome=root.querySelector('.case-block:last-child .callout'),status=root.querySelector('.case-meta div:last-child dd'),outcomeHeading=root.querySelector('.case-block:last-child h3'),nextLabel=root.querySelector('.next-project span:first-child');if(outcome)outcome.textContent=p.outcome;if(status)status.textContent=p.status||'Completed';if(outcomeHeading)outcomeHeading.textContent='What the work delivered';if(nextLabel)nextLabel.textContent='Next Project'}
if(root&&p?.story){const story=p.story.map(section=>`<section class="story-section"><div class="story-copy"><p class="eyebrow">${section.kicker}</p><h2>${section.title}</h2><p>${section.text}</p></div><div class="story-media">${section.media.map(([src,caption])=>`<figure><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('')}</div></section>`).join('');root.querySelector('.gallery-two')?.remove();root.querySelector('.next-project').insertAdjacentHTML('beforebegin',`<section class="project-story"><div class="story-intro"><p class="eyebrow">Engineering process</p><h2>From front-wing loads to the chassis bulkhead.</h2></div>${story}</section>`)}
if(root&&p?.outroMedia){root.querySelector('.next-project').insertAdjacentHTML('beforebegin',`<figure class="case-media closing-media"><img class="${p.imageFit||''}" src="${p.outroMedia.src}" alt="${p.outroMedia.alt}"></figure>`)}
if(root&&p?.subprojects){root.querySelector('.next-project').insertAdjacentHTML('beforebegin',`<section class="subprojects"><p class="eyebrow">Course projects</p>${p.subprojects.map((s,i)=>`<article class="subproject"><div><span>${String(i+1).padStart(2,'0')}</span><h2>${s.title}</h2><p>${s.summary}</p><p class="callout">PLACEHOLDER — ${s.details}</p></div><img src="${s.image}" alt="${s.title} project"></article>`).join('')}</section>`)}
if(root&&p?.subprojects){const kinetic=p.subprojects.find(project=>project.title==='Kinetic Origami');const kineticCard=[...root.querySelectorAll('.subproject')].find(card=>card.querySelector('h2')?.textContent==='Kinetic Origami');if(kinetic&&kineticCard){const details=kineticCard.querySelector('.callout');if(details)details.textContent=kinetic.details;kineticCard.insertAdjacentHTML('beforeend',`<div class="subproject-gallery">${kinetic.gallery.map(([src,caption])=>`<figure><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('')}</div>`)}}
if(root&&p?.subprojects){const bluetooth=p.subprojects.find(project=>project.title==='Bluetooth Car');const bluetoothCard=[...root.querySelectorAll('.subproject')].find(card=>card.querySelector('h2')?.textContent==='Bluetooth Car');if(bluetooth&&bluetoothCard){const details=bluetoothCard.querySelector('.callout');if(details)details.textContent=bluetooth.details;bluetoothCard.insertAdjacentHTML('beforeend',`<div class="subproject-gallery">${bluetooth.gallery.map(([src,caption])=>`<figure><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('')}</div>`)}}
if(root&&p?.subprojects){const helix=p.subprojects.find(project=>project.title==='Helix Sound Machine');const helixCard=[...root.querySelectorAll('.subproject')].find(card=>card.querySelector('h2')?.textContent==='Helix Sound Machine');if(helix&&helixCard){const details=helixCard.querySelector('.callout');if(details)details.textContent=helix.details;helixCard.insertAdjacentHTML('beforeend',`<div class="subproject-gallery">${helix.gallery.map(([src,caption])=>`<figure><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('')}</div>`)}}
if(root&&p?.video){root.querySelector('.next-project').insertAdjacentHTML('beforebegin',`<section class="gallery-two"><figure><video controls playsinline preload="metadata" src="${p.video.src}"></video><figcaption>${p.video.caption}</figcaption></figure></section>`)}
